# Generated by Django 5.0.2 on 2024-03-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(choices=[('question', 'سؤال'), ('post', 'منشور'), ('article', 'مقال')], default='post', max_length=10, verbose_name='نوع المنشور')),
                ('title_post', models.CharField(max_length=250, verbose_name='عنوان المنشور')),
                ('slug_post', models.SlugField(max_length=250, unique='True', verbose_name='اللينك')),
                ('body', models.TextField(max_length=500, verbose_name='محتوي المنشور')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'published')], default='DF', max_length=2, verbose_name='حالة المنشور')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب المنشور')),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'منشورات',
            },
        ),
    ]
